### ISSUE TITLE
Take slices instead of vectors

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [baku4/libdivsufsort-rs#1]
Hey! Thanks for this library, very convenient :)

Currently all functions take a `text: &Vec<u8>`, but it would be more convenient (and in most places sufficient) to instead take arguments as a slice: `text: &[u8]`.

Would you be open to changing this?

**Comment by baku4** [comment]
You are right, using slices is a better design.
I have updated the function arguments from `&Vec<T>` to `&[T]` and released version 0.1.3 to crates.io.

Thanks for pointing this out!

**Comment by RagnarGrootKoerkamp** [comment]
Awesome! Thanks :)
